vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

require("nvim-tree").setup({
  view = {
    adaptive_size = true
  },
  filters = {
    custom = {
      ".git",
      "node_modules",
      "bin",
      "obj",
      ".idea",
      ".nuke",
      ".vscode",
      ".editorconfig",
      "*.csproj",
      ".cache",
      ".DS_Store",
      ".gitignore",
      ".gitmodules",
      ".gitkeep",
      ".gitattributes",
      ".swp",
      ".lock",
      ".env",
      ".env.local",
      ".env.development.local",
      ".env.test.local",
      ".env.production.local",
      ".env.development",
      ".env.test",
      ".env.production",
      ".eslintcache",
      ".eslintignore",
      ".prettierignore",
      ".prettierrc",
      ".prettierrc.js",
      ".prettierrc.json",
      ".prettierrc.yml",
      ".prettierrc.yaml",
      ".stylelintignore",
      ".stylelintrc",
      ".stylelintrc.json",
      ".stylelintrc.yaml",
      ".stylelintrc.yml",
      ".stylelintrc.js",
      ".stylelintcache",
      ".huskyrc",
      ".huskyrc.json",
      ".huskyrc.js",
      ".huskyrc.yaml",
      ".huskyrc.yml",
      ".lintstagedrc",
      ".lintstagedrc.json",
      ".lintstagedrc.js",
      ".lintstagedrc.yaml",
      ".lintstagedrc.yml",
      ".commitlintrc",
      ".commitlintrc.json",
      ".commitlintrc.js",
      ".commitlintrc.yaml",
      ".commitlintrc.yml",
      ".browserslistrc",
      ".browserslistrc.json",
      ".browserslistrc.js",
      ".browserslistrc.yaml",
      ".browserslistrc.yml",
      ".babelrc",
      ".babelrc.json",
      ".babelrc.js",
      ".babelrc.mjs",
      ".babelrc.cjs",
      ".babelignore",
      ".eslintrc",
      ".eslintrc.js",
      ".eslintrc.cjs",
      ".eslintrc.yaml",
      ".eslintrc.yml",
      ".eslintrc.json",
      ".eslintrc.json5",
      ".eslintignore",
      ".eslintcache",
      ".prettierrc",
      ".prettierrc.js",
      ".prettierrc.cjs",
      ".prettierrc.yaml",
      ".prettierrc.yml",
      ".prettierrc.json"
    },
  }
})

vim.keymap.set('n', '<c-n>', ':NvimTreeFindFileToggle<CR>')
