eval "$(/opt/homebrew/bin/brew shellenv)"

export PATH="$PATH:/Users/paulalves/Library/Application Support/JetBrains/Toolbox/scripts"

export DNET_FLAGS_NO_CACHE="--no-cache"
export DNET_FLAGS_VERBOSITY="--verbosity detailed"
export DNET_FLAGS_RESTORE="--restore"
export DNET_FLAGS_CONFIG="--configuration Debug"

alias dnet-c="dotnet clean ${DNET_FLAGS_VERBOSITY}"
alias dnet-r="dotnet restore ${DNET_FLAGS_VERBOSITY}"
alias dnet-b="dnet-c && dotnet build ${DNET_FLAGS_VERBOSITY} ${DNET_FLAGS_CONFIG} ${DNET_FLAGS_RESTORE} ${DNET_FLAGS_NO_CACHE}"

alias explore='joshuto $PWD'