eval "$(/opt/homebrew/bin/brew shellenv)"

export PATH="$PATH:/Users/paulalves/Library/Application Support/JetBrains/Toolbox/scripts"

# nuget.config settings
# !! replace empty strings by credentials !!

export GH_TOPO_USER=""
export GH_TOPO_PAT=""

export GH_PAULALVES_USER=""
export GH_PAULALVES_PAT=""
